import {
  ClerkProvider
} from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from 'react-toastify'
import { AppProvider } from '@/context/AppContext'
import { headers } from 'next/headers'
import ShowNavbar from '@/components/showNavbar'
import { Toaster } from '@/components/ui/sonner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}
const PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const headersList = await headers();
  const pathname = headersList.get('x-invoke-pathname') || ''; // Get the pathname from headers
  const hideNavbar = pathname.startsWith('/embed') || pathname.startsWith('/public');

  return (
    <ClerkProvider publishableKey={PUBLISHABLE_KEY}>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning={true}>
          <AppProvider>
            {!hideNavbar && (
              <header >
                <ShowNavbar />
              </header>
            )}
            {children}
            <ToastContainer />
            <Toaster position='top-center' />

          </AppProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}